parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''
    user_identifiant: 'presleylupon@gmail.com'
    user_password: 'presley972lupon'

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Impulse For Life
    version: 1.0.0
    eager_loading:
        enabled: true
    collection:
        pagination:
            page_parameter_name: _page
            partial: true
    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 404
        
            
    # Varnish integration, remove if unwanted
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
